name: Build and Package (Intel)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # 1. MUDANÇA: Usando runner com processador Intel
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        # 2. MUDANÇA: Arquitetura definida para Intel (x64)
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip install --no-cache-dir pyinstaller==6.3.0

    - name: Build executables
      run: |
        # Gera o executável para Intel
        pyinstaller --clean --noconfirm consolidador.spec
        pyinstaller --noconfirm gerenciador.spec

    - name: Rename .app bundles
      run: |
        # 3. MUDANÇA: Renomeia os bundles para refletir a arquitetura Intel
        mv "dist/Consolidador.app" "dist/Consolidador-intel.app"
        mv "dist/Gerenciador.app" "dist/Gerenciador-intel.app"

    - name: Create DMG
      run: |
        brew install create-dmg
        
        # 4. MUDANÇA: Cria DMG a partir do app Intel
        create-dmg \
          --volname "Consolidador" \
          --volicon "assets/icon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "Consolidador-intel.app" 200 190 \
          --hide-extension "Consolidador-intel.app" \
          --app-drop-link 600 185 \
          "dist/Consolidador-intel.dmg" \
          "dist/Consolidador-intel.app"
         
        echo "Pausing for 5 seconds to prevent resource busy errors..."
        sleep 5  

        create-dmg \
          --volname "Gerenciador" \
          --volicon "assets/icon.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "Gerenciador-intel.app" 200 190 \
          --hide-extension "Gerenciador-intel.app" \
          --app-drop-link 600 185 \
          "dist/Gerenciador-intel.dmg" \
          "dist/Gerenciador-intel.app"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        # 5. MUDANÇA: Nome do artefato reflete a arquitetura Intel
        name: macos-apps-intel
        path: |
          dist/*-intel.app
          dist/*-intel.dmg
        retention-days: 7

    - name: Create release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        # 6. MUDANÇA: Arquivos da release são os DMGs Intel
        files: |
          dist/Consolidador-intel.dmg
          dist/Gerenciador-intel.dmg
        draft: false
        prerelease: false
        generate_release_notes: true